# Generated by Django 3.2.22 on 2023-11-01 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('alumnoid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correoelectronico', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('asignaturaid', models.AutoField(primary_key=True, serialize=False)),
                ('nombreasignatura', models.CharField(max_length=100)),
                ('descripcionasignatura', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('profesorid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correoelectronico', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('claseid', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.CharField(max_length=50)),
                ('fecha_clase', models.DateField()),
                ('aula', models.CharField(max_length=50)),
                ('Asignaturas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.asignaturas')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.profesores')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('asistenciaid', models.AutoField(primary_key=True, serialize=False)),
                ('fechaasistencia', models.DateField()),
                ('estadoasistencia', models.CharField(max_length=20)),
                ('alumnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.alumnos')),
                ('clases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.clases')),
            ],
        ),
    ]
